### ISSUE TITLE
kbb crawler

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#2]
kbb website is dynamic. Cannot get the price of different cars with different id?

**Comment by Winbobob** [comment]
You mean "vehicleid"? I check the website, in a short time the vehicleid is not change, I don't know what will happen after a longer time.

**Comment by alannsp** [comment]
That is because the car value is dropping as times goes and car value for a specific car id is constant. So kbb is changing the car id for a specific car dynamically to reflect the change in car values.

**Comment by Winbobob** [comment]
OK, I understand.
