### ISSUE TITLE
Subscribe not working?

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#22]

**Comment by Winbobob** [comment]
Because what we need is the webservice, we just need transfer Json file to webservice with unified format. And I can generate Json file successfully.

**Comment by Winbobob** [comment]
Wo even don't need a Json file. We can transfer the info using Json format to webserver directly.

**Comment by dragonfly90** [comment]
But we still need a file to store the data, maybe sql.
