### ISSUE TITLE
I think we need a light-weighted database on web application

### ISSUE THREAD

**Issue by Winbobob** [SuperCh-SE-NCSU/ProjectScraping#24]
[Describe the scenario] Each time user click "Subscribe" button, a automatically generated Json file will transfer to webserver. And webserver accept this file and add information to detabase.

**Comment by dragonfly90** [comment]
Maybe we can use xml first because the data is small.
Check https://docs.python.org/2/library/xml.etree.elementtree.html

**Comment by dragonfly90** [comment]
how to write xml
http://luisartola.com/software/2010/easy-xml-in-python/

**Comment by Winbobob** [comment]
Just because the data is small, we need Json instead. Json is better.
http://cloud-elements.com/json-better-xml/
https://blog.udemy.com/json-vs-xml/
......

**Comment by dragonfly90** [comment]
Ok. You can transfer the users.xml to users.json and complete the read and write function

**Comment by Winbobob** [comment]
Finally, we use the PostgreSQL.
