### ISSUE TITLE
Add select options on web page.

### ISSUE THREAD

**Issue by Winbobob** [SuperCh-SE-NCSU/ProjectScraping#29]
Because our user may be not remember the car's model and maker all the time. So we plan to design a drop down list and let users to choose. 
We had better to use some Javascript, which will increase the user experience.

**Comment by dragonfly90** [comment]
Yes, the model and make can be from be txt I gave you last time

**Comment by Winbobob** [comment]
Can u send me again? THX

**Comment by Winbobob** [comment]
I have already add it.
