### ISSUE TITLE
web framework

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#3]
which web framework should we use, I found one named lpthw.web for python

**Comment by Winbobob** [comment]
I find some https://wiki.python.org/moin/WebFrameworks. I will compare them and choose one.

**Comment by Winbobob** [comment]
I decide to use Django. Its very popular.

**Comment by Winbobob** [comment]
Finally, we use lpthw.web, just one version of web.py
