### ISSUE TITLE
Connect to Heroku remote database in python?

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#32]
I can only find one in command line
https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku

**Comment by Winbobob** [comment]
heroku pg:pull ｛HEROKU_POSTGRESQL_RED｝ ｛my_database_production｝ --app ｛rocky-spire-5172｝
