### ISSUE TITLE
The website didn't work well on firefox?

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#34]
![screenshot from 2015-02-26 16 48 19](https://cloud.githubusercontent.com/assets/4010644/6402668/75f6e6c2-bdd7-11e4-9833-018d38ed2e8c.png)

**Comment by Winbobob** [comment]
Two possibilities:
1. You browser do not load bootstrap.min.css file;
2. The resolution of your browser is too big.

**Comment by dragonfly90** [comment]
The resolution is too small
