### ISSUE TITLE
Python unit testing framework

### ISSUE THREAD

**Issue by alannsp** [SuperCh-SE-NCSU/ProjectScraping#37]
There are kind of unit testing framework,like PyUnit, unittest, Nose(extend to unittest). which one is the best for general standard unit testing?

**Comment by Winbobob** [comment]
I think each of them are OK. I recommand Nose personally.

**Comment by dragonfly90** [comment]
unittest now ?

**Comment by Winbobob** [comment]
Yes, I have already write unit tests for "modelkbb_v1_debug.py" and "modelCragList_v2_debug.py". And both of them are passed.
