### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#41]
2015-03-13T01:57:18.968931+00:00 app[web.1]: error 1372500
2015-03-13T01:57:19.120667+00:00 app[web.1]: error 1372600
2015-03-13T01:57:19.184543+00:00 app[web.1]: error 1350200

**Comment by dragonfly90** [comment]
H12 - Request timeout: An HTTP request took longer than 30 seconds to complete,

**Comment by dragonfly90** [comment]
It works well in my computer

**Comment by dragonfly90** [comment]
To debug this, use "heroku run -a rocky-spire-5172 bash"

**Comment by dragonfly90** [comment]
I get the error:
This IP has been automatically blocked.
If you have questions, please email: blocks-b13579355258611@craigslist.org

**Comment by dragonfly90** [comment]
http://ask.metafilter.com/131234/Craigslist-automated-notifications-would-be-a-good-idea

Big problem:
Not sure, but it could be because Craig and Jim aren't really crazy about other websites trying to make money off of Craigslist. Some quotes in this article for reference. To wit:

    A few years ago, independent programmer Jeff Atwood created a service that would allow people to search multiple cities at once or even search craigslist globally. Buckmaster arranged some technical interference to kill it off. Another programmer named Ryan Sit created a service called Listpic, which scraped images from craigslist and dumped them into an interface for browsing: You could scan through all the photos from the apartment listings or see pictures of all the dogs up for adoption. Buckmaster banished Listpic, too.

posted by littlerobothead at 6:38 PM on August 26, 2009

**Comment by dragonfly90** [comment]
kbb is not working for the same reason

**Comment by alannsp** [comment]
Redeployed the app on heroku,
https://agile-forest-8537.herokuapp.com/
The issue seems disappear
It seems craigslist will block your ip it you visit it too many times.

**Comment by dragonfly90** [comment]
ip addr show, is ip blocked

**Comment by dragonfly90** [comment]
Accessing localhost From Anywhere

http://www.sitepoint.com/accessing-localhost-from-anywhere/

https://pagekite.net/

**Comment by dragonfly90** [comment]
http://projectscraping.pagekite.me

**Comment by dragonfly90** [comment]
Works if we use pagekite to map local to the website

**Comment by dragonfly90** [comment]
VCL is working
