### ISSUE TITLE
1X dynos support no more than 256 processes in heroku?

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#44]
https://devcenter.heroku.com/articles/dynos

**Comment by Winbobob** [comment]
It will cost $34.50 each month, so we do not decide to user it. Instead, we achieve the functionality that clicking the "submit" button and send email immediately.

**Comment by dragonfly90** [comment]
Actually we can run multi processes in heroku

**Comment by Winbobob** [comment]
We also try AWS, and finally we choose VCL.
