### ISSUE TITLE
Reference of our project

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#54]

**Comment by dragonfly90** [comment]
Could we find some reference of our project?

**Comment by alannsp** [comment]
Compare beautiful soup and scrapy
http://stackoverflow.com/questions/19687421/difference-between-beautifulsoup-and-scrapy-crawler

**Comment by dragonfly90** [comment]
https://github.com/scrapy/scrapy/wiki

**Comment by dragonfly90** [comment]
In the article , the main difference is that Scrapy is a Web-spider or web scraper framework(complete framework), while beautiful soup is a parsing library
