### ISSUE TITLE
What user information do we need in our web 

### ISSUE THREAD

**Issue by dragonfly90** [SuperCh-SE-NCSU/ProjectScraping#7]
user name, user email address?

**Comment by Winbobob** [comment]
I think we need user email address, but our web will be RSS subscribe. We don't need users to register. They can unsunscribe our RSS if they don't need it any more.

**Comment by dragonfly90** [comment]
Maybe in v2 we should add user login #40

**Comment by Winbobob** [comment]
User login is unnecessary
